const PDFDocument = require('pdfkit');

const SEVERITY_COLOR = { critical: '#ef4444', high: '#f97316', medium: '#f59e0b', low: '#3b82f6' };
const RISK_COLOR = { Low: '#10b981', Medium: '#f59e0b', High: '#ef4444' };

/**
 * Renders a ScanReport to a PDF buffer. Used for both the "Download" button
 * on the report page and as an email attachment — one function, one format,
 * so the two never drift out of sync with each other.
 */
function generateReportPDF(report, repoName) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // --- Header ---
    doc.fontSize(20).fillColor('#1a1a2e').text('SecureDeploy AI Scan Report', { align: 'left' });
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor('#64748b').text(repoName || 'Unknown repository');
    doc.text(new Date(report.createdAt).toLocaleString());
    doc.moveDown(1);

    // --- Summary box ---
    const riskColor = RISK_COLOR[report.riskLevel] || '#64748b';
    doc.rect(50, doc.y, 495, 70).fillOpacity(0.08).fillAndStroke(riskColor, riskColor);
    doc.fillOpacity(1);
    const boxTop = doc.y - 70 + 12;
    doc.fontSize(16).fillColor(riskColor).text(`${report.riskLevel} Risk — ${report.riskScore} pts`, 62, boxTop);
    doc.fontSize(10).fillColor('#1a1a2e')
      .text(`Status: ${report.status === 'blocked' ? 'BLOCKED' : 'ALLOWED'}   |   Branch: ${report.branch}   |   Commit: ${(report.commitSha || '').slice(0, 8)}   |   Files scanned: ${report.filesScanned}`, 62, boxTop + 24)
      .text(`Total findings: ${report.findings.length}`, 62, boxTop + 40);
    doc.y = boxTop + 60;
    doc.moveDown(1.5);

    // --- AI summary ---
    if (report.gptSummary) {
      doc.fontSize(12).fillColor('#1a1a2e').text('AI Summary', { underline: true });
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor('#374151').text(report.gptSummary, { align: 'left' });
      doc.moveDown(1);
    }

    // --- Findings ---
    doc.fontSize(12).fillColor('#1a1a2e').text(`Findings (${report.findings.length})`, { underline: true });
    doc.moveDown(0.5);

    report.findings.forEach((f, i) => {
      if (doc.y > 700) doc.addPage();
      const color = SEVERITY_COLOR[f.severity] || '#64748b';

      doc.fontSize(10).fillColor(color).text(`[${(f.severity || '').toUpperCase()}] ${f.type?.replace(/_/g, ' ')}`, { continued: false });
      doc.fontSize(9).fillColor('#64748b').text(`${f.file}${f.line ? `:${f.line}` : ''}`);
      doc.fontSize(10).fillColor('#1a1a2e').text(f.message);

      if (f.gptExplanation) {
        doc.fontSize(9).fillColor('#4b5563').text(`Explanation: ${f.gptExplanation}`);
      }
      if (f.gptFix) {
        doc.fontSize(9).fillColor('#10b981').text(`Suggested fix: ${f.gptFix}`);
      }
      if (f.prUrl) {
        doc.fontSize(9).fillColor('#667eea').text(`Fix PR: ${f.prUrl}`);
      }
      doc.moveDown(0.8);
    });

    doc.fontSize(8).fillColor('#9ca3af').text('Generated by SecureDeploy AI — AI-powered deployment safety', 50, 780, { align: 'center', width: 495 });

    doc.end();
  });
}

module.exports = { generateReportPDF };
